# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-LoggedAuthDBI
version:      0.11
version_from: LoggedAuthDBI.pm
installdirs:  site
requires:
    Apache::AuthDBI:               0.93
    DBI:                           1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
